# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest


steps:
- script: echo Hello, world Hehe!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'README.md'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: 'README.zip'
    replaceExistingArchive: true

- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world